ARTIFACTS_DIR: "artifacts"
MODEL:
  trainable_backbone: true
  d: 256
  n_patches: 64
  enc_n_heads: 8
  enc_n_layers: 6
  dec_n_heads: 8
  dec_n_layers: 6
  dec_n_queries: 10
  n_classes: 20
WEIGHTS:
  valid_weight: 1
  invalid_weight: 0.1
  l1_weight: 5
  giou_weight: 2
DATA:
  root_dir: "data/"
  img_size: [256, 256]
  batch_size: 8
OPTIM:
  optimizer: "AdamW"
  lr: 0.0001
  accumulate_gradient: False
  accumulate_gradient_iters: 8
  num_epochs: 100
  max_eval_iters: 10
  save_ckpt_every: 1
  eval_every: 1
  gradient_clip: 0.1
  scheduler: ""
  T_max: 100
  eta_min: 0.000001
